name: Hex Publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install NPM packages
        working-directory: apps/gust_web/assets
        run: npm install

      - name: Gust-web assets deploy
        run: |
          mix deps.get
          mix assets.deploy

      - name: Archive built assets
        run: |
          mkdir -p release_assets
          cp -r apps/gust_web/priv/static release_assets/
          cd release_assets
          tar -czf gust_static_assets.tar.gz static

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release_assets/gust_static_assets.tar.gz
          token: ${{ secrets.PUBLISH_RELEASE_GH }}

      - name: Publish gust
        working-directory: apps/gust
        env:
          HEX_API_KEY: ${{ secrets.HEX }}
          PUBLISH_DEP: true
        run: |
          mix deps.get
          mix hex.build
          mix hex.publish --yes --replace

      - name: Publish gust-web
        working-directory: apps/gust_web
        env:
          HEX_API_KEY: ${{ secrets.HEX }}
          PUBLISH_DEP: true
        run: |
          mix deps.get
          mix assets.deploy
          mix hex.build
          mix hex.publish --yes --replace

