name: Hex Publish
on:
  # Testing, update condition after merge
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '27.0'

      - name: Publish gust
        working-directory: apps/gust
        env:
          HEX_API_KEY: ${{ secrets.HEX }}
          CI: true
        run: |
          mix deps.get
          mix hex.build
          mix hex.publish --yes

